apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: ""
  source:
    path: charts/infra
    repoURL: https://github.com/farshid-25/myhelm.git
    targetRevision: master
