apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
  namespace: argocd
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /tmp/prometheus-data
