apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
