alertmanager:
  persistentVolume:
    enabled: true
    storageClass: local-path

server:
  persistentVolume:
    enabled: true
    storageClass: local-path
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

pushgateway:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi
