apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kabul
  namespace: argocd
spec:
  destination:
    namespace: team-a
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/kabul
    repoURL: https://github.com/farshid-25/myhelm.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
