apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: charts/prometheus
    repoURL: https://github.com/farshid-25/myhelm.git
    targetRevision: master
    helm:
      releaseName: prometheus
      skipTLS: true   # <-- skip certificate verification
      values: |
        server:
          persistentVolume:
            enabled: true
            existingClaim: prometheus-server-pvc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

