apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: charts/prometheus
    repoURL: https://github.com/farshid-25/myhelm.git
    targetRevision: master
    helm:
      releaseName: prometheus
      values: |
        alertmanager:
          persistentVolume:
            enabled: true
            storageClass: standard
        server:
          persistentVolume:
            enabled: true
            storageClass: standard
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 2Gi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    #   d