apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-b
  namespace: argocd
spec:
  destination:
    namespace: team-b
    server: https://kubernetes.default.svc
  project: team-b
  source:
    path: charts/team-b
    repoURL: https://github.com/farshid-25/myhelm.git
    targetRevision: master

    helm:
      valueFiles: 
        - team-b.values.yaml 

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
