apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-a
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a
  namespace: 
spec:
  destination:
    namespace: team-a
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/team-a
    repoURL: https://github.com/farshid-25/myhelm.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
