apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kabul-b
  namespace: argocd
spec:
  destination:
    namespace: team-b
    server: https://kubernetes.default.svc
  project: team-b
  source:
    path: charts/kabul
    repoURL: https://github.com/farshid-25/myhelm.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true